export const projects = [
  {
    title: 'Image Pins Website',
    description:"A social media app that gives different layout of images built with React and uses Sanity for it's data query and content management",
    image: '/images/2.png',
    tags: ['React', 'Sanity'],
    source: 'https://image-pinstack.netlify.app',
    visit: 'https://github.com/martinovance/Pinstack',
    id: 0,
  },
  {
    title: 'ClipStack',
    description: "A modern media video streaming plaform with stunning video sections, custom categories and channels pages",
    image: '/images/7.png',
    tags: ['React', 'MUI'],
    source: 'https://clipstack.netlify.app',
    visit: 'https://github.com/martinovance/clipstack',
    id: 1,
  },
  {
    title: 'Travel Companion',
    description: "An advanced web app that routes you to the restaurants, Hotels and attractions around you based on your traveling location.",
      image: '/images/6.png',
      tags: ['ReactJS', 'MUI', 'Google Maps'],
    source: 'https://gm-travelcompanion.netlify.app',
    visit: 'https://github.com/martinovance/travel_companion',
    id: 2,
  },
  {
    title: 'Modern UI/UX Restaurant Website',
    description: "A fully responsive restaurant landing page website with modern UI/UX & reactJs. All the way from design, to development, to deployment.",
      image: '/images/3.png',
      tags: ['React', 'Figma'],
    source: 'https://g5-dining.netlify.app/#home',
    visit: 'https://github.com/martinovance/g-dining-restaurant',
    id: 3,
  },
  {
    title: 'Shopify',
    description: "An interactive shopify web for shopping including customer and employee management. Built using synfusion user interface library",
      image: '/images/5.png',
      tags: ['ReactJS', 'Syncfusion'],
    source: 'https://hr-syncfusion-dashboard.netlify.app',
    visit: 'https://github.com/martinovance/syncfusion-dashborad',
    id: 4,
  },
  {
    title: 'A Blog Website',
    description: "A well designed responsive website using HTML, CSS & Jquery. It is a blog website that keep visitors updated and informed of all happenings around the world",
      image: '/images/1.png',
      tags: ['HTML', 'CSS', 'JQuery', 'Slick'],
    source: 'https://clance9ja.netlify.app',
    visit: 'https://github.com/martinovance/clance9ja',
    id: 5,
  },
];

export const TimeLineData = [
  { year: 2018, text: 'Started my journey, kicked up my graphics career', },
  { year: 2019, text: 'Started web development with the aim of joining the tech world', },
  { year: 2020, text: 'Completed front-end development on edx google & focused on JS libraries', },
  { year: 2021, text: 'Built projects using react, next and other libraries.', },
  { year: 2022, text: 'Dived deep into react libraries and UI libraries such as React router dom, react hook form, material-UI etc.', },
];

export const gallery = [
  { image: 'images/gallery12.png'},
  { image: 'images/gallery13.png'},
  { image: 'images/gallery11.png'},
  { image: 'images/gallery14.png'},
  { image: 'images/gallery01.png'},
  { image: 'images/gallery02.png'},
  { image: 'images/gallery03.png'},
  { image: 'images/gallery04.png'},
  { image: 'images/gallery05.png'},
  { image: 'images/gallery06.png'},
  { image: 'images/gallery07.png'},
  { image: 'images/gallery08.png'},
  { image: 'images/gallery09.png'},
]

export const enterprises = [
  {
    title: 'Polleasy',
    description:"Pollesay is a premier election service that provides users with election strategies on consulting, political surveys, opinion polls, exit polls, constituency profiling, election management, and parties. Polleasy helps to ensure that political/party is abreast of the elections by having first-hand knowledge and information about their standing with electorates, historical voting data, and pattern analysis to show voting trends, news, media, and information management as well as live incidence reporting and results consolidation on election day.",
    subDesc: "Election Management Solution",
    images: ['/images/js.png', '/images/react.png', '/images/reactquery.png', '/images/axios.png', '/images/mui.png', '/images/css.png'],
    tags: [ 'Multi-Tenant', 'Volp Calls', 'WebSockets', 'Data Visualization', 'Polls'],
    id: 0,
  },
  {
    title: 'Illimikit Web',
    description: "Illimikit Web is an enterprise solution that helps automate and enhance the administration, documentation, tracking, reporting, and delivery of educational content. (1.e courses and publications) for schools. It helps didgitize the learning process for schools. It caters for critical activities such as registration, lecture delivery in digital classrooms, taking assessments, visualizing results, and other school administrative functions.",
    subDesc: "Learning Management System",
    images: ['/images/react.png', '/images/reactquery.png', '/images/axios.png', '/images/js.png', '/images/mui.png', '/images/css.png'],
    tags: [ 'User Roles', 'Lectures & Assessments', 'Grading', 'Data Visualization', 'Classrooms'],
    id: 1,
  },
  {
    title: 'GloEpid',
    description: "GloEpid is a non-profit suite solely focused on infectious disease management, contact tracing, resource management, self-assessment(through chatbot), data aggregation, analysis, and visualization with th ability to predict the next pandemic. Gloepid was built to help manage pandemic and viral diseases like COVID-19 and Ebola outbreaks with the aim of making the world safer and able to predict and prevent future outbreaks",
    subDesc: "Disease Management System",
    images: ['/images/js.png', '/images/react.png', '/images/css.png'],
    tags: [ 'Global Status Update', 'Chat Bot', 'Self Test & Feedback'],
    id: 2,
  },
  {
    title: 'Nakise',
    description: "Nakise is an event management web app that brings the end-end automation solution that digitizes the entire user journey of beneficiaries and other key personas within the digital literacy program management value chain",
    subDesc: "Event Management System",
    images: ['/images/js.png', '/images/react.png', '/images/reactquery.png', '/images/axios.png', '/images/mui.png', '/images/css.png'],
    tags: [ 'Form Builder', 'Rich Text Editor', 'Assessment Module', 'Data Visualization', 'Roles & Permissions'],
    id: 3,
  },
  {
    title: 'HRMS',
    description: "HR and Payroll solution for the entire circle of human resource and payment managemnt from the enumeration of the staff data to the skills resource, payment, and performance management. The soution supports third party integration with an attendance management solution to track employee presence at work as well as for access management and guest management.",
    subDesc: "HR and Payroll Solution",
    images: ['/images/js.png', '/images/react.png', '/images/reactquery.png', '/images/axios.png', '/images/mui.png', '/images/css.png'],
    tags: [ 'Third Party Integration', 'Payment', 'Authentication', 'Work Management'],
    id: 4,
  },
];